# Generated by Django 5.1.4 on 2025-02-17 11:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="File slugs",
            ),
        ),
    ]
