# Generated by Django 5.1.4 on 2025-02-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
