# Generated by Django 5.1.4 on 2025-02-17 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_logo_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="logo_slug",
        ),
        migrations.AddField(
            model_name="project",
            name="logo_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name="Logo slugs",
            ),
        ),
    ]
